In [13]:
import numpy as np

#np.asarray(array, dtype = None, order = None)
'''
a	任意形式的输入参数，可以是，列表, 列表的元组, 元组, 元组的元组, 元组的列表，多维数组
dtype	数据类型，可选
order	可选，有"C"和"F"两个选项,分别代表，行优先和列优先，在计算机内存中的存储元素的顺序。
'''
x = [1, 2, 3]
a = np.asarray(x)
print(x)
print(a)
a = np.reshape(x, (3,1))
print(a)

[1, 2, 3]
[1 2 3]
[[1]
 [2]
 [3]]


In [14]:
a = np.asarray(x, dtype = float)
print(a)


[1. 2. 3.]


In [15]:
#numpy.frombuffer(buffer, dtype = float, count = -1, offset = 0)
'''
buffer	可以是任意对象，会以流的形式读入。
dtype	返回数组的数据类型，可选
count	读取的数据数量，默认为-1，读取所有数据。
offset	读取的起始位置，默认为0。
'''

s = b'Hello World' #bytestring
a = np.frombuffer(s, dtype = 'S1')
print(a)


[b'H' b'e' b'l' b'l' b'o' b' ' b'W' b'o' b'r' b'l' b'd']


In [16]:
#numpy.fromiter(iterable, dtype, count=-1)
'''
numpy.fromiter 方法从可迭代对象中建立 ndarray 对象，返回一维数组。
iterable	可迭代对象
dtype	返回数组的数据类型
count	读取的数据数量，默认为-1，读取所有数据
'''
list = range(5)
it = iter(list)
x = np.fromiter(it, dtype = float)
print(x)


[0. 1. 2. 3. 4.]
