In [23]:
import numpy as np



'''
ndarray对象的内容可以通过索引或切片来访问和修改，与 Python 中 list 的切片操作一样。
ndarray 数组可以基于 0 - n 的下标进行索引，切片对象可以通过内置的 slice 函数，并设置 start, stop 及 step 参数进行，从原数组中切割出一个新数组。
'''
a = np.arange(10)
s = slice(2,7,2)
print(a[s])


[2 4 6]


In [24]:
'''
以上实例中，我们首先通过 arange() 函数创建 ndarray 对象。 然后，分别设置起始，终止和步长的参数为 2，7 和 2。
我们也可以通过冒号分隔切片参数 start:stop:step 来进行切片操作：
'''
b = a[2:7:2]
print(b)

[2 4 6]


In [25]:
'''
冒号 : 的解释：如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素。如果为 [2:]，表示从该索引开始以后的所有项都将被提取。如果使用了两个参数，如 [2:7]，那么则提取两个索引(不包括停止索引)之间的项。
'''
#index, range, step. 
#Compare the differences.
b = a[5]
print(b)
b = a[2:5]
print(b)
b = a[2:7:2]
print(b)

5
[2 3 4]
[2 4 6]


In [26]:
'''
多维数组同样适用上述索引提取方法：
'''
a = np.array([[1, 2, 3], [2, 3, 4], [3, 5, 6]])
print(a)
print('\n')
print(a[1:])


[[1 2 3]
 [2 3 4]
 [3 5 6]]


[[2 3 4]
 [3 5 6]]


In [27]:
'''
切片还可以包括省略号 …，来使选择元组的长度与数组的维度相同。 如果在行位置使用省略号，它将返回包含行中元素的 ndarray。
'''
print(a)
print(a[..., 1])
print(a[1, ...])
print(a[..., 1:])


[[1 2 3]
 [2 3 4]
 [3 5 6]]
[2 3 5]
[2 3 4]
[[2 3]
 [3 4]
 [5 6]]


In [28]:
'''
NumPy 比一般的 Python 序列提供更多的索引方式。除了之前看到的用整数和切片的索引外，数组可以由整数数组索引、布尔索引及花式索引。
以下实例获取数组中(0,0)，(1,1)和(2,0)位置处的元素。
'''

#multi-indexing
x = np.array([[1, 2], [3, 4], [5, 6]])
y = x[[0, 1, 2], [0, 1, 0]]
print(y)

x = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print(x)
print('\n')
rows = np.array([[0, 0], [3, 3]])
cols = np.array([[0, 2], [0, 2]])
y = x[rows, cols]
print(rows)
print(cols)
print(y)
#[0, 0][0, 2][3, 0][3, 2]

[1 4 5]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
[[ 0  2]
 [ 9 11]]


In [34]:
'''
返回的结果是包含每个角元素的 ndarray 对象。
可以借助切片 : 或 … 与索引数组组合。如下面例子:
'''
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = a[1: 3, 1: 3] #overrange, 1,1 to 2,2
c = a[1:3, [1, 2]] #overrange, again 1,1 to 2,2
d = a[..., 1:]
print('a:', a)
print('b:', b)
print('c:', c)
print('d:', d)

a: [[1 2 3]
 [4 5 6]
 [7 8 9]]
b: [[5 6]
 [8 9]]
c: [[5 6]
 [8 9]]
d: [[2 3]
 [5 6]
 [8 9]]


In [ ]:
'''
布尔索引
我们可以通过一个布尔数组来索引目标数组。
布尔索引通过布尔运算（如：比较运算符）来获取符合指定条件的元素的数组。
以下实例获取大于 5 的元素：
'''