In [9]:
'''
NumPy 广播(Broadcast)
广播(Broadcast)是 numpy 对不同形状(shape)的数组进行数值计算的方式， 对数组的算术运算通常在相应的元素上进行。
如果两个数组 a 和 b 形状相同，即满足 a.shape == b.shape，那么 a*b 的结果就是 a 与 b 数组对应位相乘。这要求维数相同，且各维度的长度相同。
Compatible shapes
'''
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
c = a*b
print(a)
print(b)
print(c)

[1 2 3 4]
[10 20 30 40]
[ 10  40  90 160]


In [10]:
#当运算中的 2 个数组的形状不同时，numpy 将自动触发广播机制。如：
a = np.array(
    [[0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30]]
    )
b = np.array([1, 2, 3])
print(a)
print(b)
print(a + b)
print(a * b)


[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[1 2 3]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
[[ 0  0  0]
 [10 20 30]
 [20 40 60]
 [30 60 90]]


In [11]:
#4x3 的二维数组与长为 3 的一维数组相加，等效于把数组 b 在二维上重复 4 次再运算：
bb = np.tile(b, (4, 1))
print(a)
print(bb)
print(a + bb)


[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
