In [7]:
'''
NumPy 迭代数组
NumPy 迭代器对象 numpy.nditer 提供了一种灵活访问一个或者多个数组元素的方式。
迭代器最基本的任务的可以完成对数组元素的访问。
接下来我们使用 arange() 函数创建一个 2X3 数组，并使用 nditer 对它进行迭代
'''
import numpy as np
a = np.arange(6).reshape(2, 3)
print(a)
print('\n')
print('iteration:\n')
for x in np.nditer(a):
    print(x, end = ", ")
print('\n')


[[0 1 2]
 [3 4 5]]


iteration:

0, 1, 2, 3, 4, 5, 



In [8]:
'''
以上实例不是使用标准 C 或者 Fortran 顺序，选择的顺序是和数组内存布局一致的，这样做是为了提升访问的效率，默认是行序优先（row-major order，或者说是 C-order）。
这反映了默认情况下只需访问每个元素，而无需考虑其特定顺序。我们可以通过迭代上述数组的转置来看到这一点，并与以 C 顺序访问数组转置的 copy 方式做对比，如下实例：
'''
a = np. arange(6).reshape(2, 3)
print(a)
print(np.nditer(a.T))
for x in np.nditer(a.T):
    print(x, end = ", ")
print('\n')
for x in np.nditer(a.T.copy(order = 'C')):
    print(x, end = ", ")
print('\n')


[[0 1 2]
 [3 4 5]]
0, 1, 2, 3, 4, 5, 

0, 3, 1, 4, 2, 5, 



In [9]:
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print ('原始数组是：') 
print (a) 
print ('\n') 
print ('原始数组的转置是：') 
b = a.T 
print (b) 
print ('\n') 
print ('以 C 风格顺序排序：') 
c = b.copy(order='C')  
print (c)
for x in np.nditer(c):  
    print (x, end=", " )
print  ('\n') 
print  ('以 F 风格顺序排序：')
c = b.copy(order='F')  
print (c)
for x in np.nditer(c):  
    print (x, end=", " )

原始数组是：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


原始数组的转置是：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


以 C 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

以 F 风格顺序排序：
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [10]:
'''
修改数组中元素的值
nditer 对象有另一个可选参数 op_flags。 默认情况下，nditer 将视待迭代遍历的数组为只读对象（read-only），为了在遍历数组的同时，实现对数组元素值得修改，必须指定 read-write 或者 write-only 的模式。
'''
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print(a)
print('\n')
for x in np.nditer(a, op_flags = ['readwrite']):
    x[...] = 2 * x
print(a)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [11]:
#在下面的实例中，迭代器遍历对应于每列，并组合为一维数组。
'''
flags:
c_index	可以跟踪 C 顺序的索引
f_index	可以跟踪 Fortran 顺序的索引
multi_index	每次迭代可以跟踪一种索引类型
external_loop	给出的值是具有多个值的一维数组，而不是零维数组
'''
a = np.arange(0, 60, 5)
a = a.reshape(3, 4)
print(a, '\n')
for x in np.nditer(a, flags = ['external_loop'], order = 'F'):
    print(x, end = ", ")



[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]] 

[ 0 20 40], [ 5 25 45], [10 30 50], [15 35 55], 

In [12]:
'''
广播迭代
如果两个数组是可广播的，nditer 组合对象能够同时迭代它们。 假设数组 a 的维度为 3X4，数组 b 的维度为 1X4 ，则使用以下迭代器（数组 b 被广播到 a 的大小）。
'''
a = np.arange(0,60,5) 
a = a.reshape(3,4)  
print  ('第一个数组为：')
print (a)
print  ('\n')
print ('第二个数组为：')
b = np.array([1,  2,  3,  4], dtype =  int)  
print (b)
print ('\n')
print ('修改后的数组为：')
for x,y in np.nditer([a,b]):  
    print ("%d:%d"  %  (x,y), end=", " )

第一个数组为：
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


第二个数组为：
[1 2 3 4]


修改后的数组为：
0:1, 5:2, 10:3, 15:4, 20:1, 25:2, 30:3, 35:4, 40:1, 45:2, 50:3, 55:4, 