In [6]:
'''
NumPy 统计函数
NumPy 提供了很多统计函数，用于从数组中查找最小元素，最大元素，百分位标准差和方差等。 函数说明如下：
numpy.amin() 和 numpy.amax()
numpy.amin() 用于计算数组中的元素沿指定轴的最小值。
numpy.amax() 用于计算数组中的元素沿指定轴的最大值。
'''

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
print(np.amin(a, axis = 1))
print(np.amin(a, axis = 0))
print(np.amax(a, axis = 1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[1 2 3]
[3 6 9]


In [7]:
#numpy.ptp()函数计算数组中元素最大值与最小值的差（最大值 - 最小值）。
print(np.ptp(a))
print(np.ptp(a, axis = 0))
print(np.ptp(a, axis = 1))

8
[6 6 6]
[2 2 2]


In [8]:
'''
百分位数是统计中使用的度量，表示小于这个值的观察值的百分比。 函数numpy.percentile()接受以下参数。
numpy.percentile(a, q, axis)
参数说明：

a: 输入数组
q: 要计算的百分位数，在 0 ~ 100 之间
axis: 沿着它计算百分位数的轴
首先明确百分位数：

第 p 个百分位数是这样一个值，它使得至少有 p% 的数据项小于或等于这个值，且至少有 (100-p)% 的数据项大于或等于这个值。

举个例子：高等院校的入学考试成绩经常以百分位数的形式报告。比如，假设某个考生在入学考试中的语文部分的原始分数为 54 分。相对于参加同一考试的其他学生来说，他的成绩如何并不容易知道。但是如果原始分数54分恰好对应的是第70百分位数，我们就能知道大约70%的学生的考分比他低，而约30%的学生考分比他高。

这里的 p = 70。
'''

a = np.array([[10, 7, 4], [3, 2, 1]])
print(a)

#different axis
print(np.percentile(a, 50))
print(np.percentile(a, 50, axis = 0))
print(np.percentile(a, 50, axis = 1))
print(np.percentile(a, 50, axis = 1, keepdims = True))




[[10  7  4]
 [ 3  2  1]]
[6.5 4.5 2.5]
[7. 2.]
[[7.]
 [2.]]
