In [3]:
'''
NumPy 排序、条件刷选函数
NumPy 提供了多种排序的方法。 这些排序函数实现不同的排序算法，每个排序算法的特征在于执行速度，最坏情况性能，所需的工作空间和算法的稳定性。 下表显示了三种排序算法的比较。

种类	速度	最坏情况	工作空间	稳定性
'quicksort'（快速排序）	1	O(n^2)	0	否
'mergesort'（归并排序）	2	O(n*log(n))	~n/2	是
'heapsort'（堆排序）	3	O(n*log(n))	0	否
numpy.sort()
numpy.sort() 函数返回输入数组的排序副本。函数格式如下：

numpy.sort(a, axis, kind, order)
参数说明：

a: 要排序的数组
axis: 沿着它排序数组的轴，如果没有数组会被展开，沿着最后的轴排序， axis=0 按列排序，axis=1 按行排序
kind: 默认为'quicksort'（快速排序）
order: 如果数组包含字段，则是要排序的字段
'''
import numpy as np

a = np.array([[3, 7], [9, 1]])
print(a)
print(np.sort(a))
print(np.sort(a, axis = 0))
print(np.sort(a, axis = 1))


[[3 7]
 [9 1]]
[[3 7]
 [1 9]]
[[3 1]
 [9 7]]
[[3 7]
 [1 9]]


In [4]:
dt = np.dtype([('name', 'S10'), ('age', int)])
a = np.array([("raju", 21), ('anil', 25), ('ravi', 17), ("amar", 27)], dtype = dt)
print(a)
print(np.sort(a, order = 'name'))

[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]
[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [5]:
'''
numpy.argsort()
numpy.argsort() 函数返回的是数组值从小到大的索引值。
sort the numbers in the array and return the indices
'''
x = np.array([3, 1, 2])
print(x)
y = np.argsort(x)
print(y)
print(x[y])
for i in y:
    print(x[i], end = " ")




[3 1 2]
[1 2 0]
[1 2 3]
1 2 3 

In [6]:
'''
numpy.lexsort()
numpy.lexsort() 用于对多个序列进行排序。把它想象成对电子表格进行排序，每一列代表一个序列，排序时优先照顾靠后的列。
这里举一个应用场景：小升初考试，重点班录取学生按照总成绩录取。在总成绩相同时，数学成绩高的优先录取，在总成绩和数学成绩都相同时，按照英语成绩录取…… 这里，总成绩排在电子表格的最后一列，数学成绩在倒数第二列，英语成绩在倒数第三列。
'''
name = ('raju', 'anil', 'ravi', 'amar')
dv = ('f.y', 's.y', 's.y', 'f.y')
ind = np.lexsort((dv, name))
print(ind)

print([name[i] + "," +dv[i] for i in ind])

[3 1 0 2]
['amar,f.y', 'anil,s.y', 'raju,f.y', 'ravi,s.y']


In [7]:
'''
msort、sort_complex、partition、argpartition
函数	描述
msort(a)	数组按第一个轴排序，返回排序后的数组副本。np.msort(a) 相等于 np.sort(a, axis=0)。
sort_complex(a)	对复数按照先实部后虚部的顺序进行排序。
partition(a, kth[, axis, kind, order])	指定一个数，对数组进行分区
argpartition(a, kth[, axis, kind, order])	可以通过关键字 kind 指定算法沿着指定轴对数组进行分区
复数排序：
>>> import numpy as np
>>> np.sort_complex([5, 3, 6, 2, 1])
array([ 1.+0.j,  2.+0.j,  3.+0.j,  5.+0.j,  6.+0.j])
>>>
>>> np.sort_complex([1 + 2j, 2 - 1j, 3 - 2j, 3 - 3j, 3 + 5j])
array([ 1.+2.j,  2.-1.j,  3.-3.j,  3.-2.j,  3.+5.j])
partition() 分区排序：

>>> a = np.array([3, 4, 2, 1])
>>> np.partition(a, 3)  # 将数组 a 中所有元素（包括重复元素）从小到大排列，3 表示的是排序数组索引为 3 的数字，比该数字小的排在该数字前面，比该数字大的排在该数字的后面
array([2, 1, 3, 4])
>>>
>>> np.partition(a, (1, 3)) # 小于 1 的在前面，大于 3 的在后面，1和3之间的在中间
array([1, 2, 3, 4])
找到数组的第 3 小（index=2）的值和第 2 大（index=-2）的值

>>> arr = np.array([46, 57, 23, 39, 1, 10, 0, 120])
>>> arr[np.argpartition(arr, 2)[2]]
10
>>> arr[np.argpartition(arr, -2)[-2]]
57
同时找到第 3 和第 4 小的值。注意这里，用 [2,3] 同时将第 3 和第 4 小的排序好，然后可以分别通过下标 [2] 和 [3] 取得。

>>> arr[np.argpartition(arr, [2,3])[2]]
10
>>> arr[np.argpartition(arr, [2,3])[3]]
23
'''

'\nmsort、sort_complex、partition、argpartition\n函数\t描述\nmsort(a)\t数组按第一个轴排序，返回排序后的数组副本。np.msort(a) 相等于 np.sort(a, axis=0)。\nsort_complex(a)\t对复数按照先实部后虚部的顺序进行排序。\npartition(a, kth[, axis, kind, order])\t指定一个数，对数组进行分区\nargpartition(a, kth[, axis, kind, order])\t可以通过关键字 kind 指定算法沿着指定轴对数组进行分区\n复数排序：\n>>> import numpy as np\n>>> np.sort_complex([5, 3, 6, 2, 1])\narray([ 1.+0.j,  2.+0.j,  3.+0.j,  5.+0.j,  6.+0.j])\n>>>\n>>> np.sort_complex([1 + 2j, 2 - 1j, 3 - 2j, 3 - 3j, 3 + 5j])\narray([ 1.+2.j,  2.-1.j,  3.-3.j,  3.-2.j,  3.+5.j])\npartition() 分区排序：\n\n>>> a = np.array([3, 4, 2, 1])\n>>> np.partition(a, 3)  # 将数组 a 中所有元素（包括重复元素）从小到大排列，3 表示的是排序数组索引为 3 的数字，比该数字小的排在该数字前面，比该数字大的排在该数字的后面\narray([2, 1, 3, 4])\n>>>\n>>> np.partition(a, (1, 3)) # 小于 1 的在前面，大于 3 的在后面，1和3之间的在中间\narray([1, 2, 3, 4])\n找到数组的第 3 小（index=2）的值和第 2 大（index=-2）的值\n\n>>> arr = np.array([46, 57, 23, 39, 1, 10, 0, 120])\n>>> arr[np.argpartition(arr, 2)[2]]\n10\n>>> arr[np.argpartition(arr, -2)[-2]]\n57\n同时找到第 3 和第 4 小的值。注意这里，用

In [8]:
'''
numpy.argmax() 和 numpy.argmin()
numpy.argmax() 和 numpy.argmin()函数分别沿给定轴返回最大和最小元素的索引。
'''
a = np.array([[30, 40, 70], [80, 10, 20], [50, 90, 60]])
print(a)
print(np.argmax(a))

[[30 40 70]
 [80 10 20]
 [50 90 60]]
7


In [ ]:
'''
numpy.nonzero()
numpy.nonzero() 函数返回输入数组中非零元素的索引。
'''


In [ ]:
#umpy.where() 函数返回输入数组中满足给定条件的元素的索引。





In [ ]:
'''
numpy.extract()
numpy.extract() 函数根据某个条件从数组中抽取元素，返回满条件的元素。
'
''